# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-14 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='student', max_length=30),
        ),
    ]
